version: '3'

services:
    core:
        container_name: core
        build: core
        depends_on:
            mysql:
                condition: service_healthy
        volumes:
            - ./core:/core
        networks:
            - default
            - corenetwork
        ports:
            - 12000:12000/tcp
    mysql:
        container_name: mysql
        image: mysql
        volumes:
            - mysql-data:/var/lib/mysql
        environment:
            MYSQL_DATABASE: core_db
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
        networks:
            - corenetwork
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 2s
            retries: 20
    grafana:
        container_name: grafana
        image: grafana/grafana:latest
        restart: unless-stopped
        user: "0:0"
        ports:
            - 3000:3000
        volumes:
            - ./grafana:/var/lib/grafana
        networks:
            - corenetwork
            - default
    adminer:
        image: adminer
        ports:
            - 12002:8080
        environment:
            - ADMINER_DEFAULT_SERVER=mysql
            - ADMINER_DEFAULT_DB_NAME=core_db
        networks:
            - corenetwork
            - default

networks:
  corenetwork:
    external: true

volumes:
  mysql-data:
    external: false